# Uncomment the next line to define a global platform for your project

# 官方仓库源
# source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '13.0'

inhibit_all_warnings!

use_frameworks!
install! 'cocoapods', :preserve_pod_file_structure => true

def commonPods 
  
  # pod 'YYKit', :git => 'https://github.com/CoderLouie/YYKit.git', :branch => 'swift'
  pod 'SwifterKnife', :git => 'https://github.com/CoderLouie/SwifterKnife.git', :branch => 'develop'
  pod 'SnapKit', :git => 'https://github.com/CoderLouie/SnapKit.git', :branch => 'my_source'
  pod 'lottie-ios'

end

target 'PROject_dev' do
  commonPods
end

target 'PROject_dis' do
  commonPods
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end





 
