# Uncomment the next line to define a global platform for your project

# 官方仓库源
# source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '13.0'

inhibit_all_warnings!

use_frameworks!
install! 'cocoapods', :preserve_pod_file_structure => true

def commonPods 
  
  pod 'SwifterKnife', :git => 'https://github.com/CoderLouie/SwifterKnife.git', :branch => 'develop'

end

target 'Demo' do
  commonPods
end 

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end





 
